# Generated by Django 4.0.6 on 2022-10-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometa',
            name='channel_id',
            field=models.CharField(max_length=120),
        ),
    ]
