# Generated by Django 4.0.6 on 2022-10-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_videometa_channel_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoMeta',
            new_name='YouTubeVideo',
        ),
    ]
